default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: codebook
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: codebook
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: codebook
  pool: 5
  timeout: 5000



